### ISSUE TITLE
Python3 version error

### ISSUE THREAD

**Issue by clavia96** [zhangrengang/TEsorter#14]
I tried running TEsorter using the python3 version by juke but i keep getting the error below. i installed the anaconda version.

b'\nError: Failed to open binary auxfiles for /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm: use hmmpress first\n\n'.

Any idea how to fix this?

**Comment by zhangrengang** [comment]
Build the GyDB database firstly:
```
hmmpress /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm
```

**Comment by clavia96** [comment]
I did but i still got the errors.

The first error is Error: failed to open SSI index /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm.h3i

Then followed by b'\nError: Failed to open binary auxfiles for /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm: use hmmpress first\n\n'.

The script i ran is

#!/bin/bash
module load hmmer/3.1b2

hmmpress /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm

source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load anaconda/3-2020.02

TEsorter genome.final.fa.fasta -db gydb -st nucl -p 20.

Did i place the hmmpress command wrongly?

**Comment by clavia96** [comment]
I did but i still got the errors.

The first error is Error: failed to open SSI index /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm.h3i

Then followed by b'\nError: Failed to open binary auxfiles for /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm: use hmmpress first\n\n'.

The last error is  FileNotFoundError: [Errno 2] No such file or directory: './tmp/chunk_aaseq.1.fasta.domtbl'
The script i ran is

#!/bin/bash
module load hmmer/3.1b2

hmmpress /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/GyDB2.hmm

source /opt/asn/etc/asn-bash-profiles-special/modules.sh
module load anaconda/3-2020.02

TEsorter genome.final.fa.fasta -db gydb -st nucl -p 20.

Did i place the hmmpress command wrongly?

**Comment by zhangrengang** [comment]
Look the folder `/mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/` if `hmmpress` was sucessful.

**Comment by clavia96** [comment]
No, it shows this error when i try to hmmpress the file

Error: failed to open SSI index GyDB2.hmm.h3i

**Comment by zhangrengang** [comment]
Do you have permission to create file in `/mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/`?

**Comment by clavia96** [comment]
No

**Comment by clavia96** [comment]
yes i do

**Comment by zhangrengang** [comment]
You can check the premission by:
```
touch /mnt/beegfs/apps/dmc/apps/anaconda_3-2020.02/lib/python3.7/site-packages/TEsorter/database/a
```
I think you should not have the premission.

**Comment by clavia96** [comment]
Sorry, I don't have permission
