### ISSUE TITLE
DNA type transposons cannot be classified?

### ISSUE THREAD

**Issue by hechuweiran** [zhangrengang/TEsorter#15]
HI
sorry to bother you. I want to use TEsorter to classify transposons that Repeatmodeler fails to classify, but the results show that the software seems to be unable to classify transposons of DNA type.
DNA type transposons cannot be classified?
>Chr1A:3671..3701|rnd-1_family-759#Unknown Chr1A:3671..3701|rnd-1_family-759#DNA/hAT
>Chr1A:3702..3972|rnd-1_family-759#Unknown Chr1A:3702..3972|rnd-1_family-759#DNA/hAT
>Chr1A:4491..4586|rnd-1_family-544#Unknown Chr1A:4491..4586|rnd-1_family-544#DNA/hAT-Ac
>Chr1A:15383..15535|rnd-1_family-544#Unknown Chr1A:15383..15535|rnd-1_family-544#DNA/hAT-Ac
>Chr1A:19859..20089|rnd-5_family-3147#Unknown Chr1A:19859..20089|rnd-5_family-3147#DNA/PIF-Harbinger
>Chr1A:23324..23637|rnd-1_family-2#Unknown Chr1A:23324..23637|rnd-1_family-2#DNA/PIF-Harbinger
>Chr1A:24437..24541|rnd-6_family-12487#Unknown Chr1A:24437..24541|rnd-6_family-12487#DNA/hAT-Tip100
>Chr1A:27373..27686|rnd-1_family-2#Unknown Chr1A:27373..27686|rnd-1_family-2#DNA/PIF-Harbinger
>Chr1A:28495..28592|rnd-6_family-12487#Unknown Chr1A:28495..28592|rnd-6_family-12487#DNA/hAT-Tip100
>Chr1A:29927..29982|rnd-1_family-658#Unknown Chr1A:29927..29982|rnd-1_family-658#DNA/TcMar-Stowaway
>Chr1A:30124..30220|rnd-1_family-658#Unknown Chr1A:30124..30220|rnd-1_family-658#DNA/TcMar-Stowaway
>Chr1A:30360..30608|rnd-1_family-7#Unknown Chr1A:30360..30608|rnd-1_family-7#DNA/PIF-Harbinger
>Chr1A:31505..31617|rnd-5_family-139#Unknown Chr1A:31505..31617|rnd-5_family-139#DNA/PIF-Harbinger
>Chr1A:31644..31689|rnd-5_family-139#Unknown Chr1A:31644..31689|rnd-5_family-139#DNA/PIF-Harbinger
>Chr1A:34307..34569|rnd-5_family-2428#Unknown Chr1A:34307..34569|rnd-5_family-2428#DNA/PIF-Harbinger
>Chr1A:35672..35780|rnd-5_family-1497#Unknown Chr1A:35672..35780|rnd-5_family-1497#DNA/PIF-Harbinger
>Chr1A:36038..36284|rnd-5_family-6489#Unknown Chr1A:36038..36284|rnd-5_family-6489#DNA/PIF-Harbinger

**Comment by zhangrengang** [comment]
Which `-db` do you use? TEsorter is able to classify DNA TEs with `rexdb` (but not with `gydb`). TEsorter is based on protein domains. But Repeatmodeler generate consensus library for repeat masking. The consensus  sequence might break coding frame (frame shift), which may lead to failure of TEsorter.
