### ISSUE TITLE
Setup GitHub actions for Continuous integration (CI)

### ISSUE THREAD

**Issue by Juke34** [zhangrengang/TEsorter#17]
Could you set up Github Actions for CI, to automatically perform the tests when we push modifications?

**Comment by oushujun** [comment]
This is something new to me. Do you have permission to do so as a contributor?

**Comment by zhangrengang** [comment]
Hi @Juke34, how to do this setup? I do not found CI in https://github.com/zhangrengang/TEsorter/settings/actions.

**Comment by Juke34** [comment]
@oushujun I should have permission do it but do not really have time. I'm currently changing job and have to prepare the move to another country. So I'm quite busy for the next weeks. I will see what I can do.

@zhangrengang CI means Continuous Integration, it is a concept. It means we can set up a GitHub action that allow every time we push / merge  something in the repo, tests are run automatically to be check everything is still working fine. It really worths it to spend time and learn it. It will be really useful in your life, and make your developments much more easy. It can take some times to get into it, but you will eventually save time at long term.

**Comment by oushujun** [comment]
@Juke34 Congrats on your new job! Hope the move is smooth and safe. I looked into CI on github and found a tutorial: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions#create-an-example-workflow Is this what you were talking about? It seems very useful but I need some real-life examples to improvise. Please let me know if you have any ideas on what checks you want to perform for each push.
