### ISSUE TITLE
WARNING: Could not find drmaa library.

### ISSUE THREAD

**Issue by C-grapes** [zhangrengang/TEsorter#24]
Hi,  Rengang,
    I use the rice6.9.5.liban you provided to run TEsort. There are results output but the log file always shows warning "-WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library. Please specify its full path using the environment variable DRMAA_LIBRARY_PATH. " Will this affect the result?
[1.test.sh.log](https://github.com/zhangrengang/TEsorter/files/6310310/1.test.sh.log)

 

Best wish !

putao

**Comment by zhangrengang** [comment]
No effect.
