### ISSUE TITLE
Can't find executable after old school installation

### ISSUE THREAD

**Issue by oushujun** [zhangrengang/TEsorter#25]
I want to use the latest version so I run:
>git clone https://github.com/zhangrengang/TEsorter
cd TEsorter
python setup.py install

Installation finished without a problem, but the downloaded TEsorter folder did not contain an executable. To look for where it is, I run:
>which TEsorter
$ ~/las/bin/miniconda2/envs/EDTA/bin/TEsorter

It seems like the program was installed in the conda env. But if the env already has TEsorter installed, the new version won't ovewrite the old one. So I have to uninstall the existing one then redo the old school installation:
>conda remove TEsorter -y
python setup.py install

This is not an error but it was a bit confusing to me. I put what I've done here to let others know how to reinstall.

**Comment by Juke34** [comment]
No need to remove the old one, it should be overwritten isn't it?
With `which` where do you see it now?

**Comment by oushujun** [comment]
When I wrote the issue I installed multiple times but the old one was not overwritten. I just tested again with another conda env, strangely, this time the old one was replaced. The location was unchanged.

You may close the issue as the problem has gone away. Thanks!
