### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ohan-Bioinfo** [zhangrengang/TEsorter#27]
I'm Working on TEs belongs to the animal genome, I used a library containing more than 7K consensus sequences, trying to validate protein domains using TEsorter utilizing different database each time, such as Gydb- rexdb-metazoa

My question here when I use my 7k sequences as an input only, 200 out of the 7k will be included in the TSV file, some are considered as unknown.
but what about the rest? are they considered unknown as well, and why did not bein counted?
should the rest be discarded?

**Comment by zhangrengang** [comment]
I am sorry I missed your email. Regarding the rest TEs, they might have lost protein domains, or the databases do not cover their domains, or they are false positive. The GyDB only covered the domains of LTR-RTs and the rexdb-metazoa may not work well. It is better to make a confirmation with other classifers.
