### ISSUE TITLE
Can REXdb_v3_TIR.hmm be downloaded?

### ISSUE THREAD

**Issue by andreaswallberg** [zhangrengang/TEsorter#28]
Dear developers,

Thanks for a great tool! I tried running `TEsorter -st nucl -p 40 -db rexdb-tir` but the matching `REXdb_v3_TIR.hmm` file is not available in the `database` directory. Can it be downloaded from somewhere?

Cheers!

/Andreas

**Comment by zhangrengang** [comment]
I have added the hmm file in https://github.com/zhangrengang/TEsorter/tree/master/TEsorter/database.
