### ISSUE TITLE
error exit

### ISSUE THREAD

**Issue by Jianz9293** [zhangrengang/TEsorter#31]
[X_nanoraw.txt](https://github.com/zhangrengang/TEsorter/files/8163477/X_nanoraw.txt)

Dear author, I encountered an error when running the software, exit 120 is displayed. Could you please help me check the reason? I have attached the command line and log below, thank you very much

command: Exit 120                nohup TEsorter /gpfs1/home/life/dengcl/Sp_TUseq/X_assemblegenome1.fa -db rexdb-plant -p 20 -cov 20 -eval 1e-3 > X_nanoraw.file 2>&1  (wd: ~/zhoujian/TEsorter/Xnanoraw)

**Comment by zhangrengang** [comment]
The log seems to be not completely showed at the end:
```
Traceback (most recent call last):
```
Did any other information print after this line?

**Comment by zhangrengang** [comment]
It is abnormal for python Traceback and I have no sense about what is wrong. Please try with the test data and let me known what errors raise.

**Comment by zhangrengang** [comment]
A normal python traceback is like this:
```
     Traceback(most recent call last):
     File"main.py", line108, in < module >
     lumberjack()
     File"main.py", line102, in lumberjack
     bright_side_of_death()
     File"/main.py", line105, in bright_side_of_death
     return print(tuple()[0])
     IndexError: tuple index out of range
```
which will indicate where and which error raise.

**Comment by Jianz9293** [comment]
[text.txt](https://github.com/zhangrengang/TEsorter/files/8166267/text.txt)
Thank you for your reply. Conda version is 4.11.0. I just ran text, and the log is as follows.
Looks like it's working

**Comment by Jianz9293** [comment]
I did see this kind of error in the log of another running program. The other program reported the following error messages
[Y_nanoraw.txt](https://github.com/zhangrengang/TEsorter/files/8166303/Y_nanoraw.txt)
[File.txt](https://github.com/zhangrengang/TEsorter/files/8166308/File.txt)
[TEsorter.txt](https://github.com/zhangrengang/TEsorter/files/8166309/TEsorter.txt)

**Comment by zhangrengang** [comment]
The traceback also seems to be incomplete:
```
2022-03-01 20:34:26,784 -INFO- classifying the unclassified sequences by searching against the classified ones
Traceback (most recent call last):
  File "/gpfs1/home/life/dengcl/anaconda3/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs1/home/life/dengcl/anaconda3/bin/TEsorter", line 10, in <module>
    sys.exit(main())
```
Could you send me a subset of your data to me to test?

**Comment by zhangrengang** [comment]
You can extract a part of the data and test whether the issue is reproducible. If so, just send me the partial data via email (zhangrengang@ori-gene.cn) or Baidu Cloud (YunPan).

**Comment by oushujun** [comment]
Judging from the input file name they may have provided the entire genome
to TEsorter?

Shujun
