### ISSUE TITLE
How to obtain the nucleic acid sequence of RT-Domain

### ISSUE THREAD

**Issue by wensulin93** [zhangrengang/TEsorter#32]
As mentioned, the resulting sequence contains only the protein-domain sequence file.

**Comment by wensulin93** [comment]
@zhangrengang [zhangrengang](https://github.com/zhangrengang)

**Comment by zhangrengang** [comment]
The resulted `*.dom.gff3` file contains start and end positions of each domain, so you can use these information to extract nucleic acid sequences of domains from TE sequences.

**Comment by wensulin93** [comment]
> 

I actually don't know which software will do the job. What do you recommend? Trying gffread didn't work. @zhangrengang

**Comment by zhangrengang** [comment]
I have added a script `scripts/gff2seq.py`, which can be used like:
```
python3 scripts/gff2seq.py rice6.9.5.liban rice6.9.5.liban.rexdb.dom.gff3 rice6.9.5.liban.rexdb.dom.cds

```

**Comment by wensulin93** [comment]
> 

What a great job, thank you very much!

**Comment by wensulin93** [comment]
> I have added a script `scripts/gff2seq.py`, which can be used like:
> 
> ```
> python3 scripts/gff2seq.py rice6.9.5.liban rice6.9.5.liban.rexdb.dom.gff3 rice6.9.5.liban.rexdb.dom.cds
> ```

Hello again. @zhangrengang 

I just tried this script. But my generated sequence file format looks like this:

`
>CM019268.1:22142913..22144068_LTR#LTR/unknown
TGATCATGGGCAGTGCTAGAGTGTTCCAACAAATCATTGCGGGCCACGTA
GTCGTTTTGAGCTTCTGATCCGTTGGTCGCGCCTATATGGTGGTATCACG
TAATCCATCCATTGAGAGATTGACACGTGGGTTTTGTTGGGATTTACCAG
GTGACGTCCCGAAGCTTCTTGATTCGTAGAGACAGGGGGGACCCGCCGCA
TCCTATTTTCCCCACGTTTTTCAACTAGAACCTGACTTTTcctacctttt
tttctttttcttaaatcaCAAGTTGCAAAGGTGAGGACGATTTTAACTGT
TTCCTTtcgttttctatttttgtgggTTCGAAAATTGCCGCATTAGAATA
AGAATTTGAGGTCTCGGCAAACTCTGTAAATGAACAATTCTGATCATGAA
AGCAGGGCGACATGGCCCCAGAAAGGACCAAGTAACTGCACCCTTTGCAA
ATTCTTCTCAACTGCTAAGTCGGCTCCTATTCAATTATAAGTGCTTTTAT
GTTAGTGGCAGGTATTTAGCTCACTAAAGACCAATATGAGATTTGCTCCA
TCTTTAAGGTCTTTAAGTGCTATCAATTCCAAATTAGCCTTTAAGTGGGG
CCCTCCATTAGTGTATGGTGGATTTATAGTTCCAAATTTAATCAGGTGAT
TCAGTTCGCGCAAACTGACCCAGACAcctggttaaaaaaaaattcaagat
caaTTCCATAGTCTAAGATGTCTAATTAAGGTGGGATAACGAGTGGAATG
GACTGGGCCAGAATTCATGTAAGTGGATGTGTAAGTTGGATGTAGTTGTA
GCATGGTTGTTTCTTTTAaggaaaacttatttacggaggtgaatctggac
cgtccaaaacactctttGGAAGGTGCGATGCTGCAGATAGTCTTTTTGAC
GAGATGATGTGTAGAGGTCAAAACCTAACATTGTAACTTACTCAGTTTTA
TTAGACGGCTTCTTGAAGAACCACAAAATCTC
>CM019274.1:14672757..14673676_LTR#LTR/Copia
tgttggaaaatgaaattttatcgaagagaatttggtgggacccacaccac
GTGAGGTGGGCCCAACAACAGTGAACAAGTTCCATTAAgatatgaatgag
aaattgttttATTATGGGAATTGAGAAAGCCAAATGACGTGCGTGCGCGC
CGTCACGAAACACCTAAATTAGACCAGGGTCGGAGCTCATGATTCGTGGG
CCCACGACATGTGGTTCGAGGTTTGTGATCTATGGTCTAATCTAGATTGG
TTTGGAATTGATTGTGCTTTATTGGGTTTATACCATTCGCATTTGGATGG
TCCAGTTACAGAATCAATTGTGCGCAACTGATTAACGTTGGGTTGAATGC
TCAGAATAAAACTCACGatttgattatggaatcaaTTACTGGATTAATGC
TGTATcagttttctccaaaaattgaaTTCCTCGTATTCAATTCcctatat
tcaatatgaatattgaatTGGCCCTATTGAATGGGTAGCTCCCCCTATTG
AATTCTCGTATTCAATGAGAAGGCTCCTCATCGATTATATAAATGAGTTC
AGCTCTTTTGTTTCAATACACCAAAATCGAGAGCTCTTCATCTACAATAT
TGTTCTTcctttcgagagagagagagagagtacagacacaaGTTGTTCGA
CGGCAGTCTACGGCGGTGCTCGCGCTGAGTGGTAACGAGTCAACCCTGGA
GACAAAACCGaacaacctccagcaccggtgaggcggcaaatttgtcttaa
gggcaccgttgaacaaaacgggtctcggtttgcaaATTCTTGTTCCCTAT
TTACAATTTATGCTTatgtttcatattctgtaattccAATTCATGTAATA
TTCTCTTCGAttgtaaattttcagaaattagtgAAATCATTTACTGTTTT
CCGTACTATATTTTCCTACA
>CM019264.1:15941700..15942509_LTR#LTR/Gypsy
TGTAATGGGCCAAAATATCCGAAGGTTTAGAAGGTTCAAAGAGGTGACCT
TGTATACCcatcgttcagttgtctcagttcatTTACAAGTAGAAAAAGCA
TCATAACACGTCATGGCATGCGTTTCCCGAAGGATAAACGGGCCCAGAGG
ACCTCGCCGAGCTTCGGCCGTCATCTGGATGGGAGCGCCCCTTCTTCGCT
CGGTAGAACCTTCCTGTCGCTCGGAGAAGTACTCTCGCTCGGTGGGCCTT
TTGTTCACTCGGGGAACTCAATTTACGTTCGGAGCGATGGAAGTCACTCG
GTGATATGTTTACTCAGAGATTCATTCAGAAGTGGTTTTTGGGGAACGTT
CTGGAAGGTTCCGCTGAGaagcacgttcacctctctgataatTGATTGGA
CGTCTCCGCAcgatgtgacatctctgacattgacAAACGCGGCTATGCAA
TCCTCGAAGGGCGGCGTTCATTCAATGcctctgacacgtgacgtcatccg
agcgtagcatCGCGCGTGCACGGCACCTCCACCTTGTTTAGCACTCCaaa
cctttgcctataaatagaagactACCCCTTCTAAGGCAAGGGTCTGAAAC
TCTCTAAACTACACTCCTCTTTCCCCTAGCAAATATTTCTTACTATatgt
cttcttcctcctccacttactgacttgttcgtcggagcttctccccggag
gaacacccccctccAGTTTGCAGGTACGCGACGTACAGCGTCTTTCCTCT
AAAGGTTCAGCAACAAGAAGGAAGGGTCCAAGAAGATCAAGGTTAAATCA
GCCCCCCACA
>CM019267.1:20810268..20810672_LTR#LTR/Copia
TGTTGGGAatatcttgaatattttgtcccacattggttaattatgttgtt
cccaTTTTTTGTACTCTATTATAAATAAGGGTCTTGGGGGCTGCTAGGGT
TATGGTCTTTTGTTCAAGggcttagatattagggttttgttcatctctta
gaGTTCCACCAAGGGTTTGTGTCTCCCTTTTGGGTTCCATCAGAAATTTG
TCCTTAGATATCTGTTTGGTGCTTCAAGTagagttacgggtatagccggc
tctttgtttctctccccgTTTATAGTGAATCCTCTTGCTCTTTTCYCCGT
GGAGTACGTTCTTGCTTTGTACTTGagcggaaccacgtatatttttgtgt
tcttatttattgcttgttgatttgttatattctcaatttcgttttcgaca
caaca
>CM019276.1:15709917..15710323_LTR#LTR/unknown
TGAYgcagcggaattcacaagagactagttagcatACTAGTACAAACGAG
ATAGACACTCGAAtccacgagcaaaccttgcgcacaaggaaaatagagag
aaactctgaatattattgatagaaaaactgaataattgaataggttacaa
ccctttttataagaccctaatCCTAGAAATCctaaataatgtcaaaacaa
ccggcattaaagaaaagataRttcctaattaattaaaataaaatcctaat
tcttgtagaccaagaatcctaataaagttggaaattaaaatcaaaccgaa
tatGAAAAggtaataattctaacctaaacgaaaatattcctagtaaAAMT
ctttttctaaaacaataaaaataaaatatagaaactctcgaatcttgtcc
tacatca
>QEFC01004077.1:81163..81270_LTR#LTR/unknown
TGATAAGAAATGTCTGGCAAGGAAGAAAAAGTGGTCCCTTTTCCACGTAG
AAAGTTAAATGTGGTTGCTTTCACCTCTTCTTTTATTCTGGCCATACCAA
ATCATTCA
>CM019270.1:21730565..21730686_LTR#LTR/unknown
TGTTGTTTatgaaggaaaagtgtgtagggtgttaataaccctaacacata
acaatcttatttatatagacgattcacatattaaataagtaaactaagca
atgtgggactactactaatact
>CM019273.1:16232811..16233204_LTR#LTR/unknown
tgatgcagggaggcgtgtcgaaaaaagaacgcgcaacaaggacaatcacg
aataagtatgaataGAGGTActctctctacgaacacacaattatgagaaa
aactctcaaattttcattaatcaatcataaaacaactcccttagccctaa
ggcttacaactcaatttataataaactagaaatactaaaaaggaaacata
aataaggaaaaactaAATCTACGTCttagagaacaagaaaacaataaaga
ggAAATAGAATCAACCTAATTAAGAAAACTCAATATCCTAGGCAATTTAT
GCTAAAACAAAAGATTCctaataaaatattaattgcaaaataataaacta
aaatttctatatttcttaaataattaaaatatcggtctgcatca
>CM019272.1:23847569..23847805_LTR#LTR/unknown
tgatgcaatcaaaataccaaagagaatcaaagattcaaagaaagagagca
aaatcccattcaaggagataaaccccaaagggtagaggGAGAAACTAtat
ctcaatcaatatattcaatattcttaataatcaaaagctaccaaaatgag
agacaacttacctatttatagactcaaaaccctacacacactaaagacac
taaaatgacaacaatccccctaaatcctactgcatca
>CM019273.1:17138724..17139113_LTR#LTR/unknown
tgatgcagggagacgtgttggaatagaagaacgcgcaacaaggacaatca
cgaattaGTTTGAACTAGAGATACTCTCTCTACGAACAAACGATATTGAG
AAAcatctcaaattttcattaataatttCATAAAACAACTCCCTTGCCGT
GAGGCTTATAGCAATTATTTATAATAGTAGCAACCCTAGAACTaaaaagg
aaacgaaaataCTATGAAGCAACCATAATTATTGTAGGACAAGAAAACAT
GAAATAGGAAACTGACTCAACCTAAATTAGGAAATTAAATAACTCCAGAT
TAGTAATTCCAAATTATAAAAATCCTaacaaaatactcctaaaaataaaa
tactaataaagcACTAGTTTCCAAAATCTAATCTGCATCA
>CM019270.1:18579279..18579485_LTR#LTR/Copia
tattagcGGAAGTCAAGGTGGCTGATCTCCTATACTCGGCAACAATCAAT
TAGGATCAAATCTATTCCATAATTCTAGGATAATTATTCTCCTTCCATAC
TTTTATTTCCTAATTGATTGTATTCTTTTCCTACATAAGTGTAGTGGTAT
TCTGCCACTTTTCTTAATGAGAAATATAAACATATTCATCAGAAATACTT
CTTAACA
`

And the generated domain.gff file looks like this:

`CM019264.1	TEsorter	CDS	11448305	11448598	69.3	+	2	ID=CM019264.1:11447505..11449487_INT#LTR/Copia|Class_I/LTR/Ty1_copia/Ale:Ty1-GAG;gene=GAG;clade=Ale;evalue=3.3e-21;coverage=87.8;probability=0.82
CM019264.1	TEsorter	CDS	12732713	12733021	29.7	+	1	ID=CM019264.1:12730066..12736854_INT#LTR/Copia|Class_I/LTR/Ty1_copia/Ale:Ty1-GAG;gene=GAG;clade=Ale;evalue=7.3e-09;coverage=100.0;probability=0.86
CM019264.1	TEsorter	CDS	12733631	12733837	55.7	+	1	ID=CM019264.1:12730066..12736854_INT#LTR/Copia|Class_I/LTR/Ty1_copia/Ale:Ty1-PROT;gene=PROT;clade=Ale;evalue=5.7e-17;coverage=100.0;probability=0.99
CM019264.1	TEsorter	CDS	12734286	12734525	95.5	+	2	ID=CM019264.1:12730066..12736854_INT#LTR/Copia|Class_I/LTR/Ty1_copia/Ale:Ty1-INT;gene=INT;clade=Ale;evalue=3.5e-29;coverage=39.7;probability=0.99
CM019264.1	TEsorter	CDS	12735399	12735887	213.8	+	2	ID=CM019264.1:12730066..12736854_INT#LTR/Copia|Class_I/LTR/Ty1_copia/Ale:Ty1-RT;gene=RT;clade=Ale;evalue=2.5e-65;coverage=55.6;probability=0.94
CM019264.1	TEsorter	CDS	12736388	12736681	129.5	+	1	ID=CM019264.1:12730066..12736854_INT#LTR/Copia|Class_I/LTR/Ty1_copia/Ale:Ty1-RH;gene=RH;clade=Ale;evalue=8e-40;coverage=74.8;probability=0.96`


The resulting file is empty.
I tried to modify the format to get the sequence file, but it didn't work. Sorry, I'm not good at writing code. Could you please optimize the script?

Thank you.

**Comment by zhangrengang** [comment]
Because the positions in the gff3 file is based on the genome sequences (automatically converted), so you need to use the genome instead of LTR sequences as input:
```
python3 scripts/gff2seq.py genome.fasta *.dom.gff3 output.cds
```
Please check the resulted CDS sequences to prevent frame shift.

**Comment by wensulin93** [comment]
Yes, just worked!

**Comment by Wenwen012345** [comment]
A year later, these past issues are still informative!
