### ISSUE TITLE
autonomous elements for TIR

### ISSUE THREAD

**Issue by gorliver** [zhangrengang/TEsorter#33]
Hi Rengang @zhangrengang ,
Thank you for the useful tool!
I'm seeking to classify DNA transposons and identify autonomous elements.
In the output, it seems all the classified TIRs are unknown in the Complete collum, even with the TPase domains.
Do you have any suggestions to identify the autonomous elements?
Thanks!

**Comment by zhangrengang** [comment]
Hi @gorliver,
The Complete collum is only designed for LTR elements, as LTRs contain multiple domains. 
For autonomous elements, you may reduce the rule 80-80-80 to e.g., 50-30-80 (80-80-80 aims to family-level classifications in its original literature, which seems to be too high for superfamily-level classifications; but we do not have a suitable criterion for superfamily-level classifications) or try other tools such as deepTE and RepeatClassifier.
