### ISSUE TITLE
error to get phylogeny tree using LTR_tree.R script

### ISSUE THREAD

**Issue by Ravindra-Raut** [zhangrengang/TEsorter#36]
Dear zhangrengang

I was using LTR_tree.R script, for getting phylogenetic tree from output files after running iqtree. I encounter the following error:
**Error in FUN(X[[i]], ...) : object 'Clade' not found**

I am sharing both mapfile and treefile. Please check it and give the suggest.

**Comment by Ravindra-Raut** [comment]
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/14/22,
12:02:49 AM

**Comment by zhangrengang** [comment]
Hi, I cannot access your shared files. Please share the files via GitHub directly.

**Comment by Ravindra-Raut** [comment]
[https://drive.google.com/file/d/1CT-CuJODa60mhteSjwA6xPT6_bEC-4sp/view?usp=sharing](url)

**Comment by Ravindra-Raut** [comment]
[https://drive.google.com/file/d/1kZ37st8BrpFmo_uqNDbCx4RjIhZuFHGD/view?usp=sharing](url)

**Comment by Ravindra-Raut** [comment]
[https://github.com/Ravindra-Raut/mapfile-and-treefiles](url)

**Comment by Ravindra-Raut** [comment]
i sent google dive link and files also. Please check mail.

**Comment by Ravindra-Raut** [comment]
OK I got your problem. i think github link will work for you

**Comment by zhangrengang** [comment]
Which version of iqtree do you use?

**Comment by zhangrengang** [comment]
It is because iqtree2 has changed its rule to convert special characters. I have fix it. Please try again.

**Comment by Ravindra-Raut** [comment]
I used iqtree2 version

**Comment by Ravindra-Raut** [comment]
O_sativa_A123_output_e.gydb.cls.tsv
<https://drive.google.com/file/d/1kZ37st8BrpFmo_uqNDbCx4RjIhZuFHGD/view?usp=drive_web>
 O_sativa_A123_gydb_RT_output_f.treefile
<https://drive.google.com/file/d/1CT-CuJODa60mhteSjwA6xPT6_bEC-4sp/view?usp=drive_web>




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/14/22,
03:00:23 PM
