### ISSUE TITLE
Header of the .cls.tsv file

### ISSUE THREAD

**Issue by oushujun** [zhangrengang/TEsorter#4]
In the *.cls.tsv file, the header is listed in the following format. However, in the place of "Order", the true classification should be in the "Subclass" level. For the order level, it probably should be "Transposable elements", "telomere", "knobs", "tandem repeats", and something like that.

Class 1 TE: retrotransposons
--- subclass: LTR, LINE, SINE, ...
Class 2 TE: DNA transposons
--- subclass: TIR, Helitron, ...

> #TE     Order   Superfamily     Clade   Complete        Strand  Domains
Chr10_11341966_11353509#DNA/DTC TIR     EnSpm_CACTA     unknown unknown +       TPase|EnSpm_CACTA
Chr10_1407216_1416994#DNA/DTC   TIR     EnSpm_CACTA     unknown unknown -       TPase|EnSpm_CACTA
Chr10_15280546_15283837#DNA/DTM LTR     Copia   Ivana   no      +       GAG|Ivana PROT|Ivana
Chr10_15702600_15707627#DNA/DTM TIR     MuDR_Mutator    unknown unknown -       TPase|MuDR_Mutator
Chr10_18286631_18291104#DNA/DTA LTR     Copia   Ale     no      +       PROT|Ale
Chr10_19224444_19228830#DNA/DTM TIR     MuDR_Mutator    unknown unknown +       TPase|MuDR_Mutator
Chr11_23324292_23325763#DNA/DTH mixture mixture unknown unknown ?       RH|Ale TPase|hAT
Chr11_23650026_23652156#DNA/DTM LTR     Gypsy   Tekay   no      +       RT|Tekay
Chr11_24975696_24980697#DNA/DTM TIR     MuDR_Mutator    unknown unknown +       TPase|MuDR_Mutator
Chr2_19381852_19383154#DNA/DTC  Helitron        unknown unknown unknown +       HEL2|Helitron
Chr2_21518422_21522564#DNA/DTM  LTR     Gypsy   Reina   no      +       GAG|Reina PROT|Reina

Best,
Shujun

**Comment by zhangrengang** [comment]
@oushujun, based on the classification system by [Wicker et al., 2007](https://www.nature.com/articles/nrg2165), these are in the Order level, including LTR, LINE, TIR, Helitron, etc. REXdb also followed these system in Class (Class_I and Class_II) and Sub_class (Subclass_1 and Subclass_2 in Class_II) levels. Despite this system is argued, it is still reasonable.

**Comment by oushujun** [comment]
Ahh, I was confused and thought the hierarchy was order > class > family. But actually is class > order > family. In this sense, order ~ subclass > superfamily. The original classification is correct.
