### ISSUE TITLE
How to analyze the effect of transposons on plant traits in de novo transcriptome assembly.

### ISSUE THREAD

**Issue by Wenwen012345** [zhangrengang/TEsorter#41]
Hi @zhangrengang 

The species I am studying (a kind of Rhododendron) does not have a reference genome.  Now I want to know how to analyze the effect of transposons ((mainly LTR retrotransposons) on traits in this case.  Do you have any suggestions or references?  

Most of the literature I read is based on having a reference genome, but I don&#39;t currently have one for this species.  We did its non-reference transcriptome and performed de novo assembly using Trinity by ourselves. 

 I had a discussion with Oushujun about how to discover transposons in a non-reference transcriptome, and he recommended TEsorter to me, which is indeed a good method.  However, I also found later that it would be more difficult to conduct some studies without a reference genome, such as understanding the insertion position of the LTR retrotransposon.  

But I also found that through the analysis of the non-reference transcriptome, it is indeed possible to find the approximate location of the insertion of the LTR retrotransposon (we focus on this) or some key characteristics of itself.  For example, by annotating genes and transposons, if transposons are inserted inside genes, some transposons and genes may be transcribed into RNA fragments, which can be detected in the table (as shown below) .  I haven&#39;t accomplished this working yet, but I think it&#39;s basically doable.  

![image](https://user-images.githubusercontent.com/63379795/195968115-8af5294e-9aec-4082-96b4-5fa2611487a9.png)

Nonetheless, I would also like to ask further, if there is any recommended or better, more comprehensive analysis method.  Our purpose is to search for the possible changes in the traits of Rhododendron caused by LTR retrotransposons (such as their changes in expression activity or changes in insertion sites, insertion of certain key genes, etc.) during altering cultivation conditions (such as plant hormone, stress, etc.).  I think that if we can find this result, it will be of great reference value for us, that is, the change of traits caused by somatic clonal variation of Rhododendron  during the cultivation process.

At the same time, it is also worth considering that although the rhododendron species I studied did not have a reference genome, other rhododendron species had reference genomes, and they belonged to the same subgenus, which means that they are very closely related.  . I don&#39;t know if it is possible to use this, for example, use the transcriptome of the Rhododendron species we have done, map it to the reference genome of Rhododendron (whose genome has been sequenced), and determine the insertion site of the LTR retrotransposon .  I don&#39;t think so, but I can&#39;t be 100% sure.  Want to give advice and give some answers? 

Hope the above questions could be answered, thank you!.

**Comment by zhangrengang** [comment]
Hi @wensulin93 , I have no good idea, but suggest you to de novo squence the genome of your rhododendron. The closely related rhododendron genome should share many ancient (maybe > 1Mya) LTR insertions with your species, but you seems to aim to study the activated LTR-RTs that are inserting at present. These LTR-RTs are expected to be species-specific in my opinion. The genome of rhododendron is small and thus is quite cheap that you need to sequence only one cell of HiFi and HiC data in general.

**Comment by wensulin93** [comment]
> Hi @wensulin93 , I have no good idea, but suggest you to de novo squence the genome of your rhododendron. The closely related rhododendron genome should share many ancient (maybe > 1Mya) LTR insertions with your species, but you seems to aim to study the activated LTR-RTs that are inserting at present. These LTR-RTs are expected to be species-specific in my opinion. The genome of rhododendron is small and thus is quite cheap that you need to sequence only one cell of HiFi and HiC data in general.

张老师您好  @zhangrengang 
我们是在认真考虑HiFi & HiC测序的事情，就是不知道国内有没有公司推荐呢~？

**Comment by zhangrengang** [comment]
@wensulin93 您好。可以加这个微信：bio_ture。是我们的深度合作者，合作发表过两三篇杜鹃花基因组。

**Comment by Wenwen012345** [comment]
Dear Prof. Zhang @zhangrengang 

I would like to express my sincere gratitude to you for providing us with the valuable HIFI & HiC sequencing tip. Thanks to your suggestion. We have entered into the genome annotation step currently. This content could be a crucial part of my thesis. 

Once again, I extend my heartfelt appreciation to Prof. Zhang for your invaluable suggestions to our research.

Best regards, 

Wen
