### ISSUE TITLE
ModuleNotFoundError: No module named 'RunCmdsMP'

### ISSUE THREAD

**Issue by 2eYu** [zhangrengang/TEsorter#42]
Hi, rengang

    TEsorter is very cool!!!but I have a problem: I use `conda install -c bioconda tesorter` to install TEsorter in my linux server, I installed it successfully. The output of `TEsorter input_file -db rexdb-plant` is normal, but when I ran `concatenate_domains.py HFgenome.fa.mod.LTR.intact.fa.rexdb-plant.cls.pep GAG PROT RH RT INT > HFgenome.fa.mod.LTR.intact.fa.rexdb-plant.cls.pep.full.aln` command, error occurred: `Traceback (most recent call last):
  File "~/miniconda3/envs/TEsorter/bin/concatenate_domains.py", line 7, in <module>
    from RunCmdsMP import run_cmd
ModuleNotFoundError: No module named 'RunCmdsMP'`. Could you kind enough to tell me why this occurs and how to run the command correctly?

best wishes

**Comment by zhangrengang** [comment]
Hi @2eYu.
Please refer to https://github.com/zhangrengang/TEsorter/issues/34 (the last comment).
`RunCmdsMP.py` is in `~/miniconda3/envs/TEsorter/lib/python*/site-packages/TEsorter*/TEsorter/modules/`, but is not found from `PYTHONPATH`. You can link it into `PYTHONPATH` or `~/miniconda3/envs/TEsorter/bin/`. It should work.

**Comment by 2eYu** [comment]
Hi @zhangrengang 

Thanks for your quick reply, I used this command 
`~/miniconda3/pkgs/tesorter-1.3.0-py_0/site-packages/TEsorter/modules/concatenate_domains.py HFgenome.fa.mod.LTR.intact.fa.rexdb-plant.cls.pep GAG PROT RH RT INT > HFgenome.fa.mod.LTR.intact.fa.rexdb-plant.cls.pep.full.aln2`
It finally worked. Thank you!!!

**Comment by zhangrengang** [comment]
Hi @Juke34, can you please update the TEsorter (the last verion 1.4.6) in conda? I have fixed some bugs and added new features.

**Comment by Juke34** [comment]
Sure but you must make a proper release (https://github.com/zhangrengang/TEsorter/releases) with description of lastest modifications.
Oh actually I see that the version 1.4 didn't went well into bioconda (https://github.com/bioconda/bioconda-recipes/pull/33660) I must first fix this one.

**Comment by zhangrengang** [comment]
Thanks @Juke34. I have made a new release v1.4.6.
