### ISSUE TITLE
Insertion time calculation

### ISSUE THREAD

**Issue by tinyfallen** [zhangrengang/TEsorter#45]
Dear developer,

Thanks for your great tools! 
Would you please add the function to calculate LTR insertion time in the package so that the user could take the convinence to finish the task all-in-one. 

Best ~

**Comment by 2eYu** [comment]
Maybe you can use [EDTA](https://github.com/oushujun/EDTA) to calculate LTR insertion time, but you need to add the correct parameter u(Neutral mutation rate). The default u is 1.3e-8 (per bp per year, from rice), which is not so universal for other species, so you need to calculate the neutral mutation rate(suits the species of your research) on your own.

**Comment by 2eYu** [comment]
Hi @tinyfallen,

Maybe you can use [EDTA](https://github.com/oushujun/EDTA) to calculate LTR insertion time, but you need to add the correct parameter u(Neutral mutation rate). The default u is 1.3e-8 (per bp per year, from rice), which is not so universal for other species, so you need to calculate the neutral mutation rate(suits the species of your research) on your own.

**Comment by tinyfallen** [comment]
> Hi @tinyfallen,
> 
> Maybe you can use [EDTA](https://github.com/oushujun/EDTA) to calculate LTR insertion time, but you need to add the correct parameter u(Neutral mutation rate). The default u is 1.3e-8 (per bp per year, from rice), which is not so universal for other species, so you need to calculate the neutral mutation rate(suits the species of your research) on your own.

Hi 2eYu,

Thanks for your suggestion! I would have a try.

Best ~

**Comment by zhangrengang** [comment]
@tinyfallen Sorry that it is beyond the scope of TEsorter which is a classifier based on domains but has no information of LTR regions. You may try LTR_retriver or EDTA as suggested by @2eYu .

**Comment by tinyfallen** [comment]
> 

Thanks a lot for your timely reply, I would take your suggestions and have a try !
