### ISSUE TITLE
How to obtain the set of distances between LTRs and their adjacent genes?

### ISSUE THREAD

**Issue by Wenwen012345** [zhangrengang/TEsorter#49]
Dear @zhangrengang 

Hello! I always get a satisfactory answer to my questions from you.

This time I would like to know how can I calculate the distance between each LTR and neighboring genes? Although I can think of some ways to do it, it might be more difficult for me to do it myself. So I would like to hear from you, the expert. Although I am aware of some methods to find overlaps between LTRs and genes (e.g. using gffcompare), I am not quite sure how to calculate the distance between an LTR and the nearest neighbour gene. The description of the process in the only available literature is also quite limited (for example,https://www.nature.com/articles/s41467-020-18771-4, https://academic.oup.com/hr/article/10/1/uhac241/6775201). I would therefore be interested in learning some methods here from you. Thanks!

Thank you very much for your valuable time and expertise, and I look forward to your reply and guidance.
Best regards!
wen

**Comment by zhangrengang** [comment]
Maybe `bedtools closest` and/or `bedtools intersect` meet your requirements.

**Comment by Wenwen012345** [comment]
Thanks! I'll try that later!

**Comment by Wenwen012345** [comment]
> Maybe `bedtools closest` and/or `bedtools intersect` meet your requirements.

Hi, I've just found a method that might work.
https://doi.org/10.1101/2022.10.09.511471
