### ISSUE TITLE
Add -f for hmmpress

### ISSUE THREAD

**Issue by oushujun** [zhangrengang/TEsorter#5]
I updated from the last version and use `sh build_database.sh` to rebuild hmm profiles. I got the following information and yet `TEsorter` still asked me to rebuid hmm profiles. So I think it would be good to use the `-f` option for hmmpress to overwrite any prebuilt libraries.

\# hmmpress :: prepare an HMM database for faster hmmscan searches
\# HMMER 3.2.1 (June 2018); http://hmmer.org/
\# Copyright (C) 2018 Howard Hughes Medical Institute.
\# Freely distributed under the BSD open source license.
\# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmpress [-options] <hmmfile>

Options:
  -h : show brief help on version and usage
  -f : force: overwrite any previous pressed files
SSI index file database/GyDB2.hmm.h3i already exists;
Delete old hmmpress indices first
SSI index file database/REXdb_protein_database_metazoa_v3.hmm.h3i already exists;
Delete old hmmpress indices first
SSI index file database/REXdb_protein_database_viridiplantae_v3.0.hmm.h3i already exists;
Delete old hmmpress indices first
SSI index file database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm.h3i already exists;
Delete old hmmpress i

Best,
Shujun

**Comment by zhangrengang** [comment]
I have fixed it.
