### ISSUE TITLE
Can not find SINEs 

### ISSUE THREAD

**Issue by dzaccook** [zhangrengang/TEsorter#6]
Hi,
I get the output successfully, but I can not find the SINEs, which can be classified in other soft. And I search the files in TEsorter/database/REXdb_protein_database*, it does not seems to exist.
Is there any problem?
Thank you!

**Comment by zhangrengang** [comment]
It is expected, as SINEs contain none protein domains. TEsorter has weak ability to classify non-autonomous TEs. Only those similar with autonomous TEs might be classified.

**Comment by zhangrengang** [comment]
@dzaccook, see [Limitations.3](https://github.com/zhangrengang/TEsorter#limitations).

**Comment by dzaccook** [comment]
Thank you!
