### ISSUE TITLE
Which domain defines the superfamily

### ISSUE THREAD

**Issue by iriirica** [zhangrengang/TEsorter#63]
Hello,
Thanks for the great tools.

If I understand correctly, TEsorter classifies LTR-RTs based on concatenated RT–RH–INT domains. However, a portion of LTRs do not contain all these domains clearly, in some cases, mixtures were found.

For example, TEsorter identifies the following LTR as mixture, because RT and INT domains respectively belong to different superfamily
```
Chr1:153360303..153366680  LTR     mixture unknown unknown +       RT|Retrovirus INT|Ty3_gypsy
```
But about these LTRs below, I have no idea about which domains have priority to define the superfamily
```
Chr11:87741318..87729070   LTR     Gypsy   unknown no      +       GAG|Ty3_gypsy INT|Ty3_gypsy RT|Retrovirus RH|Retrovirus
Chr5:354025327..354008436  LTR     Gypsy   unknown no      ?       INT|Ty3_gypsy PROT|Retrovirus RT|Retrovirus RH|Ty3_gypsy
```

**Comment by zhangrengang** [comment]
Thanks for your feedback. It appears I didn't address this aspect adequately. In the updated version of TEsorter, we have revised the classification approach to handle cases like the ones you've mentioned. Please try the version.

Regarding the last two LTRs you've mentioned, the updated version will also classify them as "mixture". For other LTRs, 
where there is uncertainty about which domains should take priority in defining the superfamily, we will implement a simple majority rule. This means that if more domains align with one superfamily than another, the LTR will be classified accordingly.

**Comment by iriirica** [comment]
Thank you so much for your prompt response and quick fixing!
I have one more question. While the majority rule is indeed the solution, I was wondering whether the identified results of RT RH, and INT domains are inherently more reliable compared to GAG and PROT domains?

**Comment by zhangrengang** [comment]
Perhaps, but it is challenging to define a weight for different domains. And there are limited 'mixture' elements in general.

**Comment by iriirica** [comment]
Thanks again!
