### ISSUE TITLE
The subfamilies found by TEsorter

### ISSUE THREAD

**Issue by YTLogos** [zhangrengang/TEsorter#9]
Hi @zhangrengang 
Thank you so much for developing this great tool. I tried this tool and it worked well. But I am a little confused about the results. Based on some published papers, such as [this one](https://www.nature.com/articles/s41467-018-07974-5) about rice, It reported about 300 subfamilies. The TEsorter just report ~40 subfamilies. So waht is the differences between them? Is the different tools or databases caused the different results?  Does this kind of classification by TEsorter represent the diversity of all the superfamilies? 

Thanks again for your great work!

Best,
YTLogos

**Comment by zhangrengang** [comment]
They are in different classification systems. The Clade level by TEsorter might be somewhat equivalent to the Family level in the rice paper. For detailed classification, see the [description](http://repeatexplorer.org/?page_id=918) or the [raw paper](https://doi.org/10.1186/s13100-018-0144-1) of the REXdb database. REXdb is greatly systematic in plant LTR Copia and Gypsy superfamilies but weaker in other superfamilies. It is still representative but [limited](https://github.com/zhangrengang/TEsorter#limitations) by protein domains, e.g. non-autonomous TEs may be lost.

**Comment by YTLogos** [comment]
> They are in different classification systems. The Clade level by TEsorter might be somewhat equivalent to the Family level in the rice paper. For detailed classification, see the [description](http://repeatexplorer.org/?page_id=918) or the [raw paper](https://doi.org/10.1186/s13100-018-0144-1) of the REXdb database. REXdb is greatly systematic in plant LTR Copia and Gypsy superfamilies but weaker in other superfamilies. It is still representative but [limited](https://github.com/zhangrengang/TEsorter#limitations) by protein domains, e.g. non-autonomous TEs may be lost.

Thank you for your prompt reply！Could you please tell me some softwares to classify the TEs to the family level as the same as the rice paper? Because the clade level by TEsorter is too large and It need a large of computer sources to analyze. I have searched for a long time but I failed to find a useful tool to classify TEs to the Family level in the rice paper. It will be helpful if you could suggest some methods. Thanks!

Best,
YTLogos

**Comment by zhangrengang** [comment]
Sorry, I do not know alternative tools to classify the TEs to the family level as the same as the rice paper.The authors of the paper should know. 
TEsorter is quite fast. I do not realize what you mean about "the clade level by TEsorter is too large and It need a large of computer sources to analyze".

**Comment by YTLogos** [comment]
> Sorry, I do not know alternative tools to classify the TEs to the family level as the same as the rice paper.The authors of the paper should know.
> TEsorter is quite fast. I do not realize what you mean about "the clade level by TEsorter is too large and It need a large of computer sources to analyze".

That's OK. Thanks for your reply.  I just need to identify a single consensus sequence of each TE family for downsream analysis.
